export const contexts_table = [
  {
    "context": 1,
    "agent": "Heinz",
    "text": "Heinz\'s wife has recently fallen ill and needs an expensive medication that is not covered by her medical insurance. They don\'t have the money needed to purchase the expensive prescription, but they know that it\'s vital for her to have it if she is going to recover.",
    "alt_text": "Heinz\'s dog has recently fallen ill and needs an expensive medication that is not covered by his insurance. He doesn't have the money needed to purchase the expensive prescription, but he knows that it\'s vital for her to have it if she is going to recover.",
    "action_1": "commit credit card fraud",
    "action_2": "go on strike for better wages",
    "action_3": "search for the medication on the black market",
    "action_4": "start a fundraiser",
    "action_5": "switch insurance plans",
    "action_6": "take out a loan",
    "downstream_event": "After doing this, Heinz gets into serious financial trouble. His wife has to go without medication, and she soon gets more ill."
  },
  {
    "context": 2,
    "agent": "Josh",
    "text": "Josh is on the way to the airport to catch a flight to a hunting safari in Africa. He leaves with plenty of time to make it there, but his car breaks down on the highway. Now Josh is sitting in his car near a busy intersection, and knows he needs to get to airport soon if he is going to catch his flight.",
    "alt_text": "Josh is driving at night to the airport to catch a flight to a hunting safari in Africa. He leaves with plenty of time to make it there, but his car breaks down. Now Josh is sitting in his car on an empty road in a remote area without cell service and knows he needs to get to airport soon if he is going to catch his flight.",
    "action_1": "call a taxi",
    "action_2": "demand that the airline delays the flight",
    "action_3": "reschedule for a later flight",
    "action_4": "steal a passing driver's car",
    "action_5": "take a public bus",
    "action_6": "try to convince a passing driver to trade cars",
    "downstream_event": "Josh does not make his originally scheduled flight, so other people going on the safari have to wait for him."
  },
  {
    "context": 3,
    "agent": "Brian",
    "text": "Brian is the evening manager at a bakery. Near the end of the day, he realizes that $50.75 is missing from the register and that he is responsible for accounting for the money at the end of the day. Brian knows he has to make sure the register is balanced or he might lose his job.",
    "alt_text": "Brian is the evening manager at a bakery. Near the end of the day, he realizes that $500.75 is missing from the register and that he is responsible for accounting for the money at the end of the day. His manager will be there to close up in 5 minutes and Brian knows he has to make sure the register is balanced or he might lose his job.",
    "action_1": "explain the situation to his boss",
    "action_2": "get an advance payday loan",
    "action_3": "overcharge the next customers",
    "action_4": "pay the money from his own wallet",
    "action_5": "sell one of his kidneys",
    "action_6": "stage a robbery",
    "downstream_event": "After the owner of the bakery finds out what happened, she fires the entire staff working that day."
  },
  {
    "context": 4,
    "agent": "Liz",
    "text": "Liz decides to go to the gym on her lunch break to play a game of racquetball with a friend. When she gets to the gym, she realizes that her membership has expired since she last went. Since she left her phone at her desk in the office, she has no way of letting her friend know.",
    "alt_text": "Liz decides to go to the gym on her lunch break to play a game of racquetball with a friend. When she gets to the gym, she finds out she's been temporarily banned from the gym for not paying her dues. Since she left her phone at her desk in the office, she has no way of letting her friend know she can't get in.",
    "action_1": "borrow someone's phone",
    "action_2": "crawl past the front desk",
    "action_3": "lie that she left her card inside",
    "action_4": "pay for a day-pass to the gym",
    "action_5": "pull the fire alarm",
    "action_6": "renew her membership",
    "downstream_event": "Despite doing this, Liz cannot get into the gym, and she misses the racquetball game with her friends. Without Liz, her friends do not have enough players and must cancel the game."
  },
  {
    "context": 5,
    "agent": "Mary",
    "text": "Mary is about to go to her final class of the day when she remembers that there is a homework assignment that is due. Mary\'s mom accidentally took her homework assignment out of her backpack when she was making room for her lunch. Now Mary has nothing to turn in for credit.",
    "alt_text": "Mary is about to go to her final class of the day when she remembers that there is a homework assignment that is due. When she opens her backpack, she discovers her water bottle leaked and completely dissolved her homework. Now Mary has nothing to turn in for credit.",
    "action_1": "bring in the assignment the next day",
    "action_2": "call her mom",
    "action_3": "copy a friend's assignment",
    "action_4": "hypnotize the teacher",
    "action_5": "lie that her house burnt down",
    "action_6": "quickly try to redo the assignment",
    "downstream_event": "After Mary does this, her teacher gives her a zero as her grade for the assignment."
  },
  {
    "context": 6,
    "agent": "Brad",
    "text": "Brad and some friends are hiking through the mountains in the Canadian wilderness. A couple of days into their hike, Brad realizes that they are lost. He knows that a rescue crew could arrive before long, but it is extremely cold and they don\'t have much food or water left.",
    "alt_text": "Brad and some friends are hiking through the mountains in the Canadian wilderness. A couple of days into their hike, Brad realizes that they have gotten lost and are far off their planned route. He knows that they aren't far from a town at the base of the mountain. It is extremely cold and they don\'t have much food or water left.",
    "action_1": "boost morale with a three-legged race",
    "action_2": "collect wood to start a fire",
    "action_3": "huddle to conserve energy",
    "action_4": "search for a water source",
    "action_5": "steal all of the food and water",
    "action_6": "throw away all of the food",
    "downstream_event": "After Brad does this, he and his friends spend several days lost in the woods, cold, hungry, and thirsty."
  },
  {
    "context": 7,
    "agent": "Darya",
    "text": "Darya is on her way to a concert with her friends. As they approach the entrance her friend Ted realizes he forgot his ticket at his house. The concert is about to start and Ted would likely miss most of the concert if he returned to his house for his ticket.",
    "alt_text": "Darya is on her way to a concert to celebrate her friend Ted's birthday with his friends. As they approach the entrance Ted realizes he forgot his ticket at his house. The concert is completely sold out, and Ted would likely miss most of the concert if he returned to his house for his ticket.",
    "action_1": "give her ticket to Ted",
    "action_2": "go without Ted",
    "action_3": "pretend they are conjoined twins",
    "action_4": "steal someone else's ticket",
    "action_5": "teleport into the concert",
    "action_6": "try to buy a ticket off another person",
    "downstream_event": "After Darya does this, the concert staff at the entrance become suspicious of Darya and her friends and refuse to let them in."
  },
  {
    "context": 8,
    "agent": "Eunice",
    "text": "Eunice is sunbathing at the beach next to a family with young children. When the family is playing in the water, she sees a teenager begin to go through their belongings but she isn\'t sure whether or not he\'s part of the family.",
    "alt_text": "Eunice is sunbathing at the beach next to a family with young children. When the family is playing in the water, she sees a teenager begin to throw all their belongings into the ocean. She isn\'t sure whether or not he\'s part of the family.",
    "action_1": "ask the parents if they know him",
    "action_2": "keep an eye on him",
    "action_3": "make cat noises at him until he leaves",
    "action_4": "read his mind", 
    "action_5": "tackle him and hold him down",
    "action_6": "wave to the parents",
    "downstream_event": "After Eunice does this, the family begins to feel uncomfortable about Eunice\'s behavior and decides to leave the beach for the day."
  },
  {
    "context": 9,
    "agent": "Eamon",
    "text": "Eamon is driving home on a two-lane road and thinks the driver ahead of him is intoxicated. The car has been slowly drifting between the two lanes and is currently driving in the middle of road.",
    "alt_text": "Eamon is driving home on a two-lane road and thinks the driver ahead of him is his friend Chuck, who always likes to play tricks on him. The car has been slowly drifting between the two lanes and is currently driving in the middle of road.",
    "action_1": "honk an angry message in Morse code",
    "action_2": "honk at the driver until they pull over",
    "action_3": "pull over and call 911",
    "action_4": "ram into the car",
    "action_5": "tailgate the car",
    "action_6": "take a detour at the next exit",
    "downstream_event": "After Eamon does this, he drifting car crashes into another car, resulting in a pileup accident."
  },
  {
    "context": 10,
    "agent": "Cameron",
    "text": "Cameron is filling up his car at a gas station on his way home from work when a woman approaches him to ask for a ride to a nearby city. The city is in the same direction as his house but it\'s 10 miles further than he planned to go.",
    "alt_text": "Cameron is filling up his car at a gas station on his way home from work when he runs into a childhood friend. After talking for a few minutes, she asks for a ride to a nearby city. The city is in the same direction as his house but it\'s 10 miles further than he planned to go.",
    "action_1": "call her a cab",
    "action_2": "refuse to drive her",
    "action_3": "steal whatever she has on her",
    "action_4": "take her to his house but no further",
    "action_5": "turn invisible",
    "action_6": "yell in gibberish until she leaves",
    "downstream_event": "After Cameron tries to do this, the woman attempts to walk all the way to her destination. As a result, the woman is late."
  },
  {
    "context": 11,
    "agent": "Erica",
    "text": "Erica is leaving the mall on a hot summer day. In the parking lot, she notices a dog in the back of a car without any of its windows open. The dog is panting heavily and looks tired.",
    "alt_text": "Erica is leaving the mall on a cool rainy day. In the parking lot, she notices a dog in the back of a car without any of its windows open.",
    "action_1": "ask to use the mall's loudspeaker",
    "action_2": "call emergency services",
    "action_3": "check that the doors are locked",
    "action_4": "light a fire under the car",
    "action_5": "pour water on the car to cool it",
    "action_6": "slash the tires",
    "downstream_event": "The dog dies inside the car before anyone else arrives to help."
  },
  {
    "context": 12,
    "agent": "Carl",
    "text": "Carl is a chef on his way to a food festival in Chicago. He is in line to go through security at the airport when he realizes he accidentally brought a large knife in his bag.",
    "alt_text": "Carl is a chef on his way to a food festival in Chicago. He is in line to go through security at the airport when he realizes he accidentally brought a large knife in his bag. The knife was illegally imported from Japan and Carl could be heavily fined for having it on him.",
    "action_1": "ask to check the knife",
    "action_2": "hide the knife in someone else's bag",
    "action_3": "pretend the knife is part of a hip replacement",
    "action_4": "store the knife in an airport locker",
    "action_5": "take a train instead",
    "action_6": "threaten security with the knife",
    "downstream_event": "The airport security becomes suspicious of Carl, so they take him in custody and he ends up missing the festival."
  },
  {
    "context": 13,
    "agent": "Daniel",
    "text": "Daniel is the ring bearer at his sister\'s wedding. 10 minutes into the ceremony, he reaches into his pocket but the ring isn\'t there. He realizes he left it on the seat next to him in the taxi.",
    "alt_text": "Daniel is the ring bearer at his sister\'s wedding. When he is asked to present the ring, he reaches into his pocket but the ring isn\'t there. He realizes he left it on the seat next to him in the taxi.",
    "action_1": "blame it on the maid of honor",
    "action_2": "borrow their mom\'s wedding ring",
    "action_3": "call the taxi company",
    "action_4": "run away",
    "action_5": "steal someone else\'s ring",
    "action_6": "tell his sister as soon as possible",
    "downstream_event": "When his sister finds out her ring is missing, she is disappointed and decides to cancel the wedding."
  },
  {
    "context": 14,
    "agent": "Andy",
    "text": "Andy\'s mother just died and without her, his father is unable to take care of himself. Andy can\'t afford to put his father in a retirement home and his apartment has barely enough room for one person.",
    "alt_text": "Andy\'s mother just died and without her, his father is unable to take care of himself. Andy is a wealthy investment banker with a spacious apartment.",
    "action_1": "abandon his father",
    "action_2": "buy his father a tent",
    "action_3": "check in on his father daily",
    "action_4": "get another job",
    "action_5": "move into his father\'s apartment",
    "action_6": "pitch his situation to a reality TV network",
    "downstream_event": "After Andy does this, his father\'s mental and physical health quickly deteriorates."
  },
  {
    "context": 15,
    "agent": "Ahmed",
    "text": "Ahmed is the captain of a 50-passenger cruise ship. Four days into their trip they get caught in a storm and the engine breaks under the pressure. They are now stranded at sea. A rescue boat is on its way but might not arrive for a week. Their food supplies are quickly dwindling and Ahmed isn\'t sure what to instruct the passengers and crew.",
    "alt_text": "Ahmed is the captain of a 50-passenger cruise ship. Four days into their trip they get caught in a storm and the engine breaks under the pressure. They are now stranded at sea. A rescue boat is on its way and should arrive within a day. Their food supplies are quickly dwindling and Ahmed isn\'t sure what to instruct the passengers and crew.",
    "action_1": "organize a fishing crew",
    "action_2": "ration their food",
    "action_3": "request supplies to be airdropped",
    "action_4": "sell all the food to the highest bidder",
    "action_5": "serve engine fuel to the passengers",
    "action_6": "throw disobedient passengers off the boat",
    "downstream_event": "After Ahmed tries this, several passengers suffer injuries from heatstroke and dehydration."
  },
  {
    "context": 16,
    "agent": "Eva",
    "text": "Eva and Todd are on a mountain climbing trip in Arizona. In the middle of their longest day Todd slips and gets his arm trapped in a crevice. Eva tries calling 911 but she has no service. The sun is beating down on them and Eva is worried that she might be getting dehydrated as she unsuccessfully tries to get his arm out of the rock.",
    "alt_text": "Eva and Todd are on a mountain climbing trip in Arizona. In the middle of their longest day Todd slips and gets his finger trapped in a crevice. Eva tries calling 911 but she has no service. The sun is beating down on them and Eva is worried that she might be getting dehydrated as she unsuccessfully tries to get his finger out of the rock.",
    "action_1": "get her arm stuck in solidarity",
    "action_2": "give Todd her water",
    "action_3": "hike until she finds cell service",
    "action_4": "leave Todd to save herself",
    "action_5": "saw Todd\'s arm off",
    "action_6": "yell at Todd for getting stuck",
    "downstream_event": "After Eva does this, Todd dies."
  },
  {
    "context": 17,
    "agent": "Jeff",
    "text": "Jeff works the night shift at a 24/7 convenience store. Every day at 7am the owner of the store, Jeff's boss, takes over for the morning shift. Today, Jeff has an important court appointment at 8am but his boss hasn't shown up yet and isn't returning his calls.",
    "alt_text": "Jeff works the night shift at a 24/7 convenience store. Every day at 7am the owner of the store, Jeff's boss, takes over for the morning shift. Today, Jeff has an important court appointment at 8am. It's currently 6 am and his boss hasn't shown up yet.",
    "action_1": "ask a friend to take over",
    "action_2": "call his lawyer",
    "action_3": "leave the store unattended",
    "action_4": "lock up the store",
    "action_5": "stage a break-in at the store",
    "action_6": "tell his lawyer that he\'s sick",
    "downstream_event": "After the owner returns, she fires him."
  },
  {
    "context": 18,
    "agent": "Shania",
    "text": "Shania is competing in a 100-mile dogsledding race in Minnesota. She hopes to come in first and use the prize money to pay for her college tuition. Halfway through the race she finds one of her competitors lying unconscious next to his crashed sled.",
    "alt_text": "Shania is competing in a 100-mile dogsledding race in Minnesota. She hopes to come in first and use the prize money to pay for her college tuition. Halfway through the race she finds one of her competitors sitting next to his sled smoking a cigarette.",
    "action_1": "call for help",
    "action_2": "carry her competitor on her sled",
    "action_3": "finish the race",
    "action_4": "hide him in the snow",
    "action_5": "leave her dogs with him",
    "action_6": "steal his dogs for extra speed",
    "downstream_event": "When the competition judges find out what happened, they cancel the race and no one wins the prize money."
  }
]

